### ISSUE TITLE
Feature request: add option to  attach an image to each payment. 

### ISSUE THREAD

**Issue by leo123215** [emavgl/oinkoin#133] opened 2024-07-17 07:45 UTC
Implementing a feature to store copies of recipes would enhance the documentation of spending and would allow a finer tracking.

**Comment by emavgl** [comment] 2024-08-29 05:28
I am closing this issue as a duplicate of another one (with more description) 

https://github.com/emavgl/oinkoin/issues/142

**Closed** 2024-08-29 05:28 UTC
