### ISSUE TITLE
add translation to [Português (Brasil)]

### ISSUE THREAD

**Issue by cubiquitous** [emavgl/oinkoin#57] opened 2024-01-10 11:25 UTC
hi, I know that there's a crowdin link to add translation but i'm not sure how to add one for Português (Brasil). I would appreciate if you guide me or, if you are the one that has to create, you would open.

thx in advance

**Comment by emavgl** [comment] 2024-01-10 11:57
Hi, thanks for being interested in contributing with the translations.

I have just enabled Portuguese and Portuguese (Brazil) in Crowdin. You should be able to see them in the dashboard and continue with the translations.

Thank you

**Comment by cubiquitous** [comment] 2024-01-10 16:21
should I keep the escaped codes? ex:
![image](https://github.com/emavgl/oinkoin/assets/30845840/71471e62-7808-4abf-a92c-d9106fe20309)

**Comment by emavgl** [comment] 2024-01-10 16:39
Yes please, keep them :) it is just some break-line, otherwise it will be too long.

**Comment by emavgl** [comment] 2024-01-10 16:45
Sorry, just to clarify. It is not an escaping character but you should keep the \n which is a special character indicating the break-line.

**Comment by emavgl** [comment] 2024-01-10 18:35
@cubiquitous, when you finish, let me know, I'll merge your changes and do a release with those :)

**Comment by cubiquitous** [comment] 2024-01-10 20:13
@emavgl currently I'm having a debate with many friends that is in a draw so I'll ask you instead:

in Pt-BR there's two possible valid translations  to the word "record":
- Item
- Registro

`Registro` is more formal than normal and `Item` sounds more natural and (arguably) accessible to regular people. I honestly prefer Item, but really depends if you want something more formal or not.

**Comment by emavgl** [comment] 2024-01-10 20:22
Item is ok 👌😊 your call

**Comment by cubiquitous** [comment] 2024-01-10 20:32
then is all done.

one a sidenote, some of the context are really lacking. for instance on:
```
Key: Save
Context: -> Save
```
Save can translate to "salvar" (as in store data) or "economizar" (to save money).

I'm not sure how the context could be improved there, but it could be confusing for some. maybe put directions where one can see the original version.

**Comment by emavgl** [comment] 2024-01-10 20:36
That's totally right. There is room for improvement. I'll try adding the context.

In your case, it is meant as Store Data.

Did you make both Portuguese and Portuguese Brazil or just this last?

**Comment by cubiquitous** [comment] 2024-01-10 20:46
I did only for Portuguese Brazil (PT-BR). but if you want I can ask my brother to translate to Portuguese (PT-PT) since he lives in Portugal and can ask people about the differences (which should be very minimal).

**Comment by emavgl** [comment] 2024-01-10 20:53
No pressure - just if he has time 😉

Can I merge your changes at the moment?

**Comment by cubiquitous** [comment] 2024-01-10 20:56
> No pressure - just if he has time 😉

i'll ask him

> Can I merge your changes at the moment? 

yes. that would be great

**Comment by emavgl** [comment] 2024-01-10 21:32
Sorry, apparently I got a problem with the mapping pt_BR. I'll take some more time to test it properly, I'll probably do it tomorrow.

Thank you again for your contribution!

**Comment by cubiquitous** [comment] 2024-01-10 21:50
If I made any mistake let me know and I will correct. It's my first time doing this so I probably did something wrong somewhere.

**Comment by emavgl** [comment] 2024-01-10 21:52
No problem, in this case the problem is on my side, when importing the translation.

In any case there is surely the possibility for any fix. You can constantly update the translations and they will be live on the next release.

**Comment by cubiquitous** [comment] 2024-01-11 13:59
I checked all my translations, improved a few and found one that had an extra escape code (which I don't know where it came from). it may have been that

**Comment by emavgl** [comment] 2024-01-12 14:32
Hi

I have merged the new translations and fix the problem on my side. You should find Portoguese already available in https://github.com/emavgl/oinkoin/releases/tag/1.0.37 - soon an update will appear for Google Play, and later on F-Droid. Let me know when you have a chance to try this out.

I have added for now also Portoguese PT other than BR. At the moment, it has the same translations. Better than not having it at all, I think.

Then, I'll close this issue. But you can continue to add or modify the translations whenever you want. I'll then add the change in the next releases.

Thanks again!

**Comment by cubiquitous** [comment] 2024-01-12 18:54
so, I checked and sent to a few friends and there are feedback related to translation and another one about something else. for now i'll focus on the translation, but if you wish i'll tell the other.

- if I go `home >add symbol > try to add a new item from any category` it will appear at the top `edit record` instead of translation and `note` is also untranslated.
- the items/records itself are untranslated. there's "house, transposts, food, salary" but you probably want those to be translated too

**Comment by emavgl** [comment] 2024-01-13 12:30
Ehi, it should be fixed now, you will have it in the next release.

There was a string missing:

- Edit record

which I have tried to translate myself in Portoguese, you may want to have a look maybe.

**Comment by emavgl** [comment] 2024-01-13 15:29
fyi: Just released 1.0.39

**Comment by emavgl** [comment] 2024-01-15 12:02
No problem, thanks for the confirmation. :) I'll close this PR then. Thanks again for contributing. I'll see automatically the changes to the Portuguese version via Crowdin.

**Closed by emavgl** 2024-01-15 12:02 UTC
