### ISSUE TITLE
[BUG] Grey screen on launching since last update 1.0.51

### ISSUE THREAD

**Issue by LoHub** [emavgl/oinkoin#97] opened 2024-03-03 23:15 UTC
Hello,
First all, thank you for this very convenient app which is very helpful to me in my daily life.
Unfortunately the app does not work anymore since last update. If you need additional details, I will be very happy to provide them.

# Step to reproduce bug

* Simply launch app

# What occur

* App only show a grey screen (see joined screenshot) and it stay in this state

# Technical details

* APK used: https://github.com/emavgl/oinkoin/releases/download/1.0.51/app-arm64-v8a-pro-release.apk
* Android version: 14 (UQ1A.240205.004)
* Model: Pixel 8

# Screenshot

![screenshot](https://github.com/emavgl/oinkoin/assets/11139973/80e90eec-b06b-440b-933e-1030cb12fdf7)

**Comment by emavgl** [comment] 2024-03-03 23:20
Hi there, I am sorry to hear about the bug. Unfortunately I am not able to reproduce it on my side.

I have tried installing from the linked APK and everything worked fine.

Please procede as following:

- Download the apk for the version 1.0.49
- Install it as a normal update
- Export all the data, to be safe
- Remove the app and install 1.0.51
- Import the exported data

**Comment by emavgl** [comment] 2024-03-03 23:22
Or try to clear the Cache data first. But NOT the app data.

**Comment by emavgl** [comment] 2024-03-03 23:59
I see.

I made this APK with version 1.0.52 which points to 1.0.49. Unfortunately Github does not allow me to attach the APK directly.

You can download it from here: https://transfer.sh/6dJ5VaGhTi/app-arm64-v8a-pro-release.apk

Let me know if it works.

**Comment by emavgl** [comment] 2024-03-04 00:34
Glad that it worked :) I was not aware of that flag. I will surely add it.

Could you please try to update to the real 1.0.52 then?

Thanks for trying and sorry again for the inconvenience.

**Comment by emavgl** [comment] 2024-03-04 00:51
Ok, that's is a different bug, but not as tragic as the first one 👌 will fix asap.

**Comment by emavgl** [comment] 2024-03-09 09:53
Should be fixed with https://github.com/emavgl/oinkoin/releases/tag/1.0.54 - I am closing the issue, but feel free to comment or re-open the issue if the problem persist.

**Closed by emavgl** 2024-03-09 09:53 UTC
Labels: bug
